### Transforming Code Into Idiomatic Python
* Replace traditional index manupulation with Python core looping idiomatic

In [2]:
# Looping over a range of numbers - Traditional Approach
for i in [0,1,2,3,4,5]:
    print(i**2,end=" ")

0 1 4 9 16 25 

In [5]:
# Idotiomatic Programming
for i in range(6):
    print(i**2,end=" ")
    

0 1 4 9 16 25 

In [8]:
#Looping Over A Collection¶
colors=['red','green','yellow','purple']
for i in range(len(colors)):
    print(colors[i],end=" ")
for color in colors:
    print(color,end=" ")
    

red green yellow purple red green yellow purple 

In [10]:
#Looping Backward
colors=['red','green','yellow','purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red purple yellow green red 

# Pandas


In [20]:
import pandas as pd

In [21]:
dt = {'Id':[11,12,13,14,15],
      'first_name':['A','B','C','D','E'],
      'company':['aa','bb','cc','dd','ee'],
      'address':['hyd','hyd','hyd','hyd','hyd']}
mydt = pd.DataFrame(dt)

In [25]:
print(mydt)

   Id first_name company address
0  11          A      aa     hyd
1  12          B      bb     hyd
2  13          C      cc     hyd
3  14          D      dd     hyd
4  15          E      ee     hyd


In [26]:
import os

In [32]:
os.chdir("C:\Users\SYS-13\Desktop\python") # Saves to certain Location

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-32-da8481a06de5>, line 1)

In [34]:
mydt.to_csv('WorkingFile.csv',index=False)

### Reading the data from CSV file

In [36]:
mydata=pd.read_csv('WorkingFile.csv',skiprows=1,
                  names=["CustID","Name","Company","Address"])

In [39]:
print(mydata)

   CustID Name Company Address
0      11    A      aa     hyd
1      12    B      bb     hyd
2      13    C      cc     hyd
3      14    D      dd     hyd
4      15    E      ee     hyd


## Print only two columns

## Print the large value from custID column -- max

## Print the least value from custID column -- min

## Average of custID column -- Sum(li)/len(li)

## Numpy-working with multi demensional array

In [41]:
import numpy as np

In [43]:
li=[1,2,3,4,5]
print(li,end=" ")

[1, 2, 3, 4, 5] 

In [45]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [49]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [51]:
a1=np.array([(1,2,3),(4,5,6)])
a1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.hstack((a1,a2)))

[[1 2 3 4 5 6]]


In [55]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
